### ISSUE TITLE
Navigation icons not supported by font

### ISSUE THREAD

**Issue by adrianadermon** [kickingvegas/casual-dired#22]
The icons under the "Navigation" heading seem to use emoji unicode characters. My font (Pragmata Pro), and I assume most other fonts, don't support these characters. It would be nice if these could be customized by the user.

Thanks for sharing this nice package!

**Comment by kickingvegas** [comment]
@adrianadermon out of curiosity, do you also have issues with the following characters?

- ↑
- ↓

**Comment by kickingvegas** [comment]
@adrianadermon [v1.0.3](https://github.com/kickingvegas/casual-dired/releases/tag/1.0.3) released and now available on MELPA. Please update and confirm if default Casual Dired behavior which avoids usage of UTF-8 symbols resolves this issue. If so then please close this issue.

**Comment by kickingvegas** [comment]
Closing issue.

**Comment by adrianadermon** [comment]
Yes, this solves my issue.

The arrow symbols did work in my font (it has pretty wide unicode coverage, just not emoji).

Thanks for the quick response, and sorry for my late reply!
